[package]
name = "rust_http_server"
version = "0.1.0"
authors = ["Andromeda"]
edition = "2024"

[dependencies]
regex = "1.11.1"
clap = { version = "4.5.40", features = ["derive"] }

[profile.release]
opt-level = 3
